### ISSUE TITLE
Missing Module for Execution Trace Converter

### ISSUE THREAD

**Issue by wkaisertexas** [mlcommons/chakra#44]
## Describe the Bug

```console
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/chakra/et_converter/et_converter.py", line 9, in <module>
    from .text2chakra_converter import Text2ChakraConverter
  File "/content/chakra/et_converter/text2chakra_converter.py", line 8, in <module>
    from chakra.et_def.et_def_pb2 import (
ModuleNotFoundError: No module named 'chakra.et_def.et_def_pb2'
```

## Steps to Reproduce

```bash
git clone https://github.com/mlcommons/chakra
cd chakra
pip install -e .
python -m chakra.et_converter.et_converter --input_type PyTorch --input_filename traces/traces/cdd55a1099e8_561.1714517342978231506.pt.trace.json --output_filename traces/Chakra
```

**Comment by wkaisertexas** [comment]
Nevermind. I forgot change directors do not work in Google Collab Scripts. Yikes!
